name: hydrun CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - id: lazor
            src: .
            os: debian:bullseye
            flags: -e '--privileged -v /dev:/dev'
            cmd: lazor
            dst: Cadmium/cadmium-lazor.img.gz
          - id: duet
            src: .
            os: debian:bullseye
            flags: -e '--privileged -v /dev:/dev'
            cmd: duet
            dst: Cadmium/cadmium-duet.img.gz
          - id: kevin
            src: .
            os: debian:bullseye
            flags: -e '--privileged -v /dev:/dev'
            cmd: kevin
            dst: Cadmium/cadmium-kevin.img.gz
          - id: bob
            src: .
            os: debian:bullseye
            flags: -e '--privileged -v /dev:/dev'
            cmd: bob
            dst: Cadmium/cadmium-bob.img.gz
          # Minnie and Speedy don't build as of 2021-12-30
          # - id: minnie
          #   src: .
          #   os: debian:bullseye
          #   flags: -e '--privileged -v /dev:/dev'
          #   cmd: minnie
          #   dst: Cadmium/cadmium-minnie.img.gz
          # - id: speedy
          #   src: .
          #   os: debian:bullseye
          #   flags: -e '--privileged -v /dev:/dev'
          #   cmd: speedy
          #   dst: Cadmium/cadmium-speedy.img.gz
          - id: homestar
            src: .
            os: debian:bullseye
            flags: -e '--privileged -v /dev:/dev'
            cmd: homestar
            dst: Cadmium/cadmium-homestar.img.gz
          - id: coachz
            src: .
            os: debian:bullseye
            flags: -e '--privileged -v /dev:/dev'
            cmd: coachz
            dst: Cadmium/cadmium-coachz.img.gz

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
          sudo install /tmp/hydrun /usr/local/bin
      - name: Build with hydrun
        working-directory: ${{ matrix.target.src }}
        run: hydrun -o ${{ matrix.target.os }} ${{ matrix.target.flags }} "./Hydrunfile ${{ matrix.target.cmd }}"
      - name: Fix permissions for output
        run: sudo chown -R $USER .
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.id }}
          path: ${{ matrix.target.dst }}
  publish-linux:
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download output
        uses: actions/download-artifact@v2
        with:
          path: /tmp/out
      - name: Publish latest release alias to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          files: |
            /tmp/out/*/*
